### ISSUE TITLE
Create image success, but can't push it into registry

### ISSUE THREAD

**Issue by fanux** [containers/storage#1199]
```go
	options, err := storage.DefaultStoreOptions(unshare.IsRootless(), unshare.GetRootlessUID())
	options.GraphDriverOptions = []string{}
	options.RunRoot = "/var/container/run"
	options.GraphRoot = "/var/container/root"
	if err != nil {
		fmt.Println("err ", err)
		return err
	}
	store, err := storage.GetStore(options)
	if err != nil {
		fmt.Printf("err: %v", err)
		return err
	}

	b := bytes.NewBuffer([]byte("hello"))
	store.SetLayerBigData("foo", "key", b)

	_, err = store.CreateLayer("foo", "", nil, "", true, nil)
	fmt.Println("create layer: ", err)

	i, err := store.CreateImage("test", nil, "foo", "busybox:latest,centos:latest", nil)
	if err != nil {
		fmt.Println("create image failed", err)
		return err
	}
	fmt.Println("test: ", i, err)

	return ni
```

Why the ImageStore is nil?:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2a8dcaa]

goroutine 1 [running]:
github.com/containers/storage.(*store).CreateImage(0xc00045fe40, 0x30516c0, 0x4, 0x0, 0x0, 0x0, 0xc0007692fc, 0x3, 0x307d797, 0x1c, ...)
	/root/sealer/vendor/github.com/containers/storage/store.go:1141 +0x24a
github.com/alibaba/sealer/pkg/merge.MergeImages(0xc00080fd20, 0x0, 0x0, 0x0, 0x0, 0xc, 0x0)
	/root/sealer/pkg/merge/merge.go:32 +0x591
github.com/alibaba/sealer/sealer/cmd.glob..func9(0x4543440, 0x466a348, 0x0, 0x0)
	/root/sealer/sealer/cmd/imageMerge.go:38 +0xda
github.com/spf13/cobra.(*Command).execute(0x4543440, 0x466a348, 0x0, 0x0, 0x4543440, 0x466a348)
	/root/sealer/vendor/github.com/spf13/cobra/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x4544fc0, 0x20, 0x6, 0x7)
	/root/sealer/vendor/github.com/spf13/cobra/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/root/sealer/vendor/github.com/spf13/cobra/command.go:897
github.com/alibaba/sealer/sealer/cmd.Execute()
	/root/sealer/sealer/cmd/root.go:46 +0x31
main.main()
	/root/sealer/sealer/main.go:26 +0x35
```

**Comment by fanux** [comment]
Do we has an example to create layer, and create image?

**Comment by fanux** [comment]
Add image options and fixed:
```
	imageOptions := &storage.ImageOptions{
		Digest: digest.Digest(""),
	}

	i, err := store.CreateImage("test", nil, "foo", "busybox:latest,centos:latest", imageOptions)
```

**Comment by fanux** [comment]
I create an image:
```go
	options, err := storage.DefaultStoreOptions(unshare.IsRootless(), unshare.GetRootlessUID())
	store, err := storage.GetStore(options)

	imageOptions := &storage.ImageOptions{
		Digest: digest.Digest(""),
	}

	im, err := store.CreateImage("docker.io/fanux/merge3", nil, "", `{"signatures-sizes":{"sha256:14d4f50961544fdb669075c442509f194bdc4c0e344bde06e35dbd55af842a32":[]}}`, imageOptions)

	return nil
```

Then sucess got the image, but I can't push it into registry:
```
[root@iZ2ze4vo1tjx7vf1b0ab2tZ sealer]# buildah push docker.io/fanux/merge3
error pushing image "docker.io/fanux/merge3" to "docker://docker.io/fanux/merge3": error copying layers and metadata from "containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage]@docker.io/fanux/merge3" to "docker://fanux/merge3:latest": Error determining manifest MIME type for containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage]@docker.io/fanux/merge3: error locating item named "manifest" for image with ID "docker.io/fanux/merge3": file does not exist
```
