### ISSUE TITLE
panic nil storageReference pointer on `podman import`

### ISSUE THREAD

**Issue by vbatts** [containers/storage#305]
(while migrating nspawn machines into podman containers)

### steps
```shell
cd /var/lib/machines/mymachine/
tar -cv --acls --selinux --xattrs . | podman import - mymachine
```

### expected

successfully imported image

### encountered

```shell
panic: value method github.com/containers/libpod/vendor/github.com/containers/image/storage.storageReference.NewImageDestination called using nil *storageReference pointer

goroutine 1 [running]:
github.com/containers/libpod/vendor/github.com/containers/image/storage.(*storageReference).NewImageDestination(0x0, 0x1854fa0, 0xc00003e110, 0xc00002f340, 0xc000431760, 0x14552a0, 0x8, 0x203000)
        <autogenerated>:1 +0xe1
github.com/containers/libpod/vendor/github.com/containers/image/copy.Image(0x1854fa0, 0xc00003e110, 0xc00028cbc0, 0x1861820, 0x0, 0x1861880, 0xc00002e6e0, 0xc0003aefc0, 0x0, 0x0, ...)
        /builddir/build/BUILD/libpod-0ad9b6bf2aea4ba37e8c9738feabec61343ba175/_build/src/github.com/containers/libpod/vendor/github.com/containers/image/copy/copy.go:141 +0xfd
github.com/containers/libpod/libpod/image.(*Runtime).Import(0xc0001d89e0, 0x1854fa0, 0xc00003e110, 0x7fff92f8d617, 0x10, 0x7fff92f8d628, 0xc, 0x1841f00, 0xc00000e020, 0x0, ...)
        /builddir/build/BUILD/libpod-0ad9b6bf2aea4ba37e8c9738feabec61343ba175/_build/src/github.com/containers/libpod/libpod/image/image.go:926 +0x336
github.com/containers/libpod/libpod.(*Runtime).Import(0xc000330540, 0x1854fa0, 0xc00003e110, 0x7fff92f8d617, 0x10, 0x7fff92f8d628, 0xc, 0x27eeff0, 0x0, 0x0, ...)
        /builddir/build/BUILD/libpod-0ad9b6bf2aea4ba37e8c9738feabec61343ba175/_build/src/github.com/containers/libpod/libpod/runtime_img.go:187 +0x229
github.com/containers/libpod/pkg/adapter.(*LocalRuntime).Import(0xc000431340, 0x1854fa0, 0xc00003e110, 0x7fff92f8d617, 0x10, 0x7fff92f8d628, 0xc, 0x27eeff0, 0x0, 0x0, ...)
        /builddir/build/BUILD/libpod-0ad9b6bf2aea4ba37e8c9738feabec61343ba175/_build/src/github.com/containers/libpod/pkg/adapter/runtime.go:159 +0xde
main.importCmd(0x27ceb80, 0x0, 0x0)
        /builddir/build/BUILD/libpod-0ad9b6bf2aea4ba37e8c9738feabec61343ba175/_build/src/github.com/containers/libpod/cmd/podman/import.go:77 +0x26d
main.glob..func26(0x2628320, 0xc000514260, 0x2, 0x2, 0x0, 0x0)
        /builddir/build/BUILD/libpod-0ad9b6bf2aea4ba37e8c9738feabec61343ba175/_build/src/github.com/containers/libpod/cmd/podman/import.go:26 +0x7f
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).execute(0x2628320, 0xc00003a0e0, 0x2, 0x2, 0x2628320, 0xc00003a0e0)
        /builddir/build/BUILD/libpod-0ad9b6bf2aea4ba37e8c9738feabec61343ba175/_build/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:762 +0x473
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x262bc20, 0x6, 0x27f0b80, 0xc00018e300)
        /builddir/build/BUILD/libpod-0ad9b6bf2aea4ba37e8c9738feabec61343ba175/_build/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/containers/libpod/vendor/github.com/spf13/cobra.(*Command).Execute(0x262bc20, 0xc00053c370, 0xc0000aa058)
        /builddir/build/BUILD/libpod-0ad9b6bf2aea4ba37e8c9738feabec61343ba175/_build/src/github.com/containers/libpod/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
        /builddir/build/BUILD/libpod-0ad9b6bf2aea4ba37e8c9738feabec61343ba175/_build/src/github.com/containers/libpod/cmd/podman/main.go:225 +0x3c
```

### version

```shell
[root@knob] /var/lib/machines# podman version
Version:            1.1.2
RemoteAPI Version:  1
Go Version:         go1.11.5
Git Commit:         a95a49d3038462d033f84ac314ec8a3064a99cff
Built:              Tue Mar  5 13:10:31 2019
OS/Arch:            linux/amd64
[root@knob] /var/lib/machines# rpm -q podman
podman-1.1.2-1.git0ad9b6b.fc29.x86_64
```

**Comment by mheon** [comment]
Looks like `dest` is nil in https://github.com/containers/libpod/blob/master/libpod/image/image.go#L931

**Comment by mheon** [comment]
@vbatts I think this is Podman, not c/image or c/storage - it looks like we're handing them a null pointer at some point

**Comment by rhatdan** [comment]
It would be nice if github had a way to transfer issues from one project to another.
